### ISSUE TITLE
URLs with HTTP scheme are incorrectly handled as a local resource.

### ISSUE THREAD

**Issue by dulimarta** [Banno/polymer-2-starter-kit-webpack#4]
### Steps to reproduce

1. `git-clone` this repo
2. Run `bower install --save PolymerElements/paper-styles`
3. Add the following line in `src/my-app.html`

    `<link rel="import" href="../bower_components/paper-styles/typography.html">`

4. Run `webpack`

You will get the following error:

    ERROR in ./bower_components/font-roboto/roboto.html
    Module not found: Error: Can't resolve '${YOUR_PROJECT_DIR}/bower_components/font-roboto/https:/fonts.googleapis.com/cssfamily=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic' in '${YOUR_PROJECT_DIR}/polymer-2-starter-kit-webpack/bower_components/font-roboto'

**Comment by AlexHenkel** [comment]
Having same issue. Any thoughts?

**Comment by ChadKillingsworth** [comment]
Can you post this issue at webpack-contrib/polymer-webpack-loader ? This repository is only for demonstrating how webpack can be used to build the polymer starter kit. Anything beyond that is out of scope for this project.
